[package]
name = "Async_Programming"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["time", "rt", "rt-multi-thread", "macros", "sync"] }
chrono = "0.4.42"