[package]
name = "Async_Programming"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
chrono = "0.4.42"
futures = "0.3.31"
reqwest = "0.13.1"
fetch-data = "0.2.0"
anyhow = "1.0.100"
scraper = "0.25.0"