[package]
name = "Files_Folders_Directories"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5.0"
tokio = { version = "1.45.1", features = ["rt", "net", "rt-multi-thread", "macros", "sync"] }
notify = "8.2.0"
